version: '3.5'

networks:
  fabric-external-chaincode-server:
    name: fabric-external-chaincode-server
    driver: bridge

services:
  orderer.dev.com:
    container_name: orderer.dev.com
    image: hyperledger/fabric-orderer:${IMAGE_TAG}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./organizations/ordererOrganizations/dev.com/orderers/orderer.dev.com/msp:/etc/hyperledger/msp
      - ./artifacts/orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050
    networks:
      - fabric-external-chaincode-server
    extra_hosts:
      - host.internal:${LOCAL_HOST_IP}

  peer0.org1.dev.com:
    container_name: peer0.org1.dev.com
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    volumes:
        - /var/run/:/host/var/run/
        - ./organizations/peerOrganizations/org1.dev.com/peers/peer0.org1.dev.com/msp:/etc/hyperledger/msp
        - ./config/core.yaml:/etc/hyperledger/fabric/core.yaml
        - ./external/bin:/builders/external/bin
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer.dev.com
    networks:
      - fabric-external-chaincode-server
    extra_hosts:
      - host.internal:${LOCAL_HOST_IP}

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${IMAGE_TAG}
    tty: true
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.dev.com
      - CORE_PEER_ADDRESS=peer0.org1.dev.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-dev
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './sh/createChannel.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./organizations/peerOrganizations/org1.dev.com/users/Admin@org1.dev.com/msp:/etc/hyperledger/msp
        - ./external:/etc/hyperledger/fabric/external
        - ./:/opt/gopath/src/chaincodedev/
    depends_on:
      - orderer.dev.com
      - peer0.org1.dev.com
    networks:
      - fabric-external-chaincode-server
    extra_hosts:
      - host.internal:${LOCAL_HOST_IP}
